{{- if not (.Values.config.database.password.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.database.password" . }}
type: Opaque
data:
  PAPERLESS_DBPASS: {{ default (randAlphaNum 20) .Values.config.database.password.value | b64enc | quote }}
{{- end }}