apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paperless.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "paperless.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
            - configMapRef:
                name: {{ include "paperless.fullname" . }}
            - secretRef:
                name: {{ include "paperless.secretKeyName" . }}
            - secretRef:
                name: {{ include "paperless.superUserName" . }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/export
              name: export
            - mountPath: /usr/src/paperless/consume
              name: consume
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "paperless.data.pvc" . }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "paperless.media.pvc" . }}
        - name: export
          persistentVolumeClaim:
            claimName: {{ include "paperless.export.pvc" . }}
        - name: consume
          persistentVolumeClaim:
            claimName: {{ include "paperless.consume.pvc" . }}
      {{- end }}
      initContainers:
      - name: init-system
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['sh', '-c', 'python /usr/src/paperless/src/manage.py migrate && python /usr/src/paperless/src/manage.py createsuperuser --noinput --username "$USERNAME" --email "$EMAIL" || true']
        envFrom:
         - configMapRef:
              name: {{ include "paperless.fullname" . }}
         - secretRef:
              name: {{ include "paperless.secretKeyName" . }}
         - secretRef:
              name: {{ include "paperless.superUserName" . }}