{{- if not (.Values.secrets.secretKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secretKeyName" . }}
type: Opaque
data:
  PAPERLESS_SECRET_KEY: {{ default (randAlphaNum 20) .Values.secrets.secretKey.key | b64enc | quote }}
{{- end }}