{{- if not (.Values.secrets.superUserPassword.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.superUserName" . }}
type: Opaque
data:
  USERNAME: {{ default "email" .Values.secrets.superUserPassword.username | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ default (randAlphaNum 20) .Values.secrets.superUserPassword.password | b64enc | quote }}
  EMAIL: {{ default "admin" .Values.secrets.superUserPassword.email | b64enc | quote }}
{{- end }}