---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  labels:
    app: paperless
  namespace: paperless-ng
data:
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_DBHOST: "postgres"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://tika:9998"
  PAPERLESS_OCR_LANGUAGE: "deu"
  PAPERLESS_ALLOWED_HOSTS: "*"
  PAPERLESS_CORS_ALLOWED_HOSTS: "http://localhost:8000"
  PAPERLESS_OCR_MODE: "skip" # skip / skip_noarchive/ redo / force
  PAPERLESS_OCR_CLEAN: "clean-final" # clean / clean-final / none
  PAPERLESS_OCR_DESKEW: "true" # true / false
  PAPERLESS_OCR_ROTATE_PAGES: "true" 
  PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: "12"
  PAPERLESS_OCR_OUTPUT_TYPE: "pdfa" # pdf / pdfa / pdfa-1 / pdfa-2 / pdfa-3
  PAPERLESS_OCR_PAGES: "0"
  PAPERLESS_OCR_USER_ARGS: ""
  PAPERLESS_TIME_ZONE: "Europe/Berlin"